# Site settings
title: Circular Ruins
author: Linus Yang
fromyear: 2011
baseurl: ""
url: "https://linusyang.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty
paginate: 10
paginate_path: "/archives/:num/"
plugins: [jekyll-paginate]

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: linusyang

# Utils
latex: true
